version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: trust-contacts
    ports: [ "5432:5432" ]
    env_file: [ .env ]
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped